"""Narrow ports at the scheduler, outbox, journal, and projection boundaries."""

from __future__ import annotations

from collections.abc import Iterable, Sequence
from contextlib import AbstractContextManager
from datetime import datetime
from typing import Any, Protocol, Self

from job_visibility.model import Attempt, Event, Finding, JobVisibility, ProjectionDecision


class SchedulerJobRepository(Protocol):
    def add(self, job: Any) -> None: ...
    def get(self, job_id: str, *, for_update: bool = False) -> Any | None: ...
    def claim_due(self, *, now: datetime, limit: int, owner: str) -> Sequence[Any]: ...


class SchedulerAttemptRepository(Protocol):
    def add(self, attempt: Any) -> None: ...
    def for_job(self, job_id: str) -> Sequence[Any]: ...


class SchedulerUnitOfWork(AbstractContextManager[Self], Protocol):
    jobs: SchedulerJobRepository
    attempts: SchedulerAttemptRepository

    def commit(self) -> None: ...
    def rollback(self) -> None: ...


class OutboxRepository(Protocol):
    def add(self, record: Any) -> None: ...
    def lease_due(self, *, now: datetime, limit: int, owner: str) -> Sequence[Any]: ...
    def mark_published(
        self, event_id: str, *, partition: int, offset: int, published_at: datetime
    ) -> None: ...
    def mark_failed(self, event_id: str, *, error: str, next_attempt_at: datetime) -> None: ...


class RawEdrRepository(Protocol):
    def scan_unprojected(self, *, limit: int) -> Sequence[Event]: ...


class VisibilityRepository(Protocol):
    def get(self, job_id: str, *, for_update: bool = False) -> JobVisibility | None: ...
    def save(self, job: JobVisibility, *, expected_version: int | None = None) -> None: ...
    def job_ids(self) -> Sequence[str]: ...


class AttemptProjectionRepository(Protocol):
    def replace_for_job(self, job_id: str, attempts: Iterable[Attempt]) -> None: ...
    def for_job(self, job_id: str) -> Sequence[Attempt]: ...


class ProjectionCheckpointRepository(Protocol):
    def contains(self, event_id: str) -> bool: ...
    def add(self, event_id: str, job_id: str, projected_at: datetime) -> None: ...


class DecisionRepository(Protocol):
    def add(self, job_id: str, decision: ProjectionDecision) -> None: ...


class FindingRepository(Protocol):
    def replace_for_job(self, job_id: str, findings: Iterable[Finding]) -> None: ...
