[alembic]
# Select a history explicitly, for example:
#   alembic -n scheduler upgrade head

[scheduler]
script_location = migrations/scheduler
prepend_sys_path = .
version_table = alembic_version_scheduler

[edr]
script_location = migrations/edr
prepend_sys_path = .
version_table = alembic_version_edr

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
